version: "3"
# This file contains the dependencies of spring-data-demo.
services:
  postgres:
    container_name: sdm-postgres
    image: postgres
    network_mode: 'bridge'
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=spring-demo-db

volumes:
  postgres-volume: { }